name: deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Installs and upgrades pip, installs other dependecies
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install build twine

      - name: Publish YOLOv5-detect to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: yolov5-detect
        run: |
          python3 -m build
          python3 -m twine upload dist/*
